# Generated by Django 5.0.6 on 2024-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_type",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
