# Generated by Django 5.0.6 on 2024-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UI", "0007_alter_match_away_goals_alter_match_home_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="flag_id",
            field=models.IntegerField(null=True),
        ),
    ]
